common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login1'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
   
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from index.views import base_views
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('todo/', include('todo.urls')),
    path('memo/', include('memo.urls')),
    path('weather/', include('weather.urls')),
    path('calendar1/', include('calendar1.urls')),



]

make_joy/config/urls.py
from django.contrib import admin
from django.urls import path, include

from index.views import base_views
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('todo/', include('todo.urls')),
    path('memo/', include('memo.urls')),
    path('weather/', include('weather.urls')),
    path('calendar1/', include('calendar1.urls')),



]

makejoy_latest/calendar1/urls.py
from django.urls import path
from . import views

app_name = 'calendar1'

urlpatterns = [
    path('', views.calendar1_view, name='calendar1_name'),
]

makejoy_latest/common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login1'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
 

]

makejoy_latest/config/urls.py
from django.contrib import admin
from django.urls import path, include

from index.views import base_views
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('todo/', include('todo.urls')),
    path('memo/', include('memo.urls')),
    path('weather/', include('weather.urls')),
    path('calendar1/', include('calendar1.urls')),

]

makejoy_latest/index/urls.py
from django.urls import path

from .views import base_views

app_name = 'index'

urlpatterns = [
    path('', base_views.index, name='index'),
]

makejoy_latest/memo/urls.py
from django.urls import path
from . import views

app_name = 'memo'

urlpatterns = [
    path('', views.memo_view, name='memo_name'),
]

makejoy_latest/password/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

appname='password'

urlpatterns = [
    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

makejoy_latest/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_view, name='todo_name'),
]

makejoy_latest/weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.weather_view, name='weather_name'),
]

index/models.py
from django.contrib.auth.models import User
from django.db import models


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

makejoy_latest/index/models.py
# from django.contrib.auth.models import User
# from django.db import models

makejoy_latest/todo/models.py
from django.db import models

# Create your models here.

makejoy_latest/weather/models.py
from django.db import models

# Create your models here.

index/forms.py
from django import forms
from index.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

makejoy_latest/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

makejoy_latest/index/forms.py
# from django import forms
# from index.models import Question, Answer

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

index/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from index.models import Question


def index(request):
    return render(request, 'index/index.html')

makejoy_latest/calendar1/views.py
from django.shortcuts import render

# Create your views here.
def calendar1_view(request):

        return render(request, 'calendar1/calendar1.html')

makejoy_latest/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

makejoy_latest/index/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

# from index.models import Question


def index(request):
    return render(request, 'index/index.html')

makejoy_latest/memo/views.py
from django.shortcuts import render

# Create your views here.
def memo_view(request):

        return render(request, 'memo/diarymemo.html')

makejoy_latest/password/views.py
from django.shortcuts import render

# Create your views here.
def password_reset(request):
    return render(request, 'password/password_reset.html')

makejoy_latest/todo/views.py
from django.shortcuts import render


def todo_view(request):

        return render(request, 'todo/todo.html')

makejoy_latest/weather/views.py
from django.shortcuts import render


def weather_view(request):

        return render(request, 'weather/weather_api.html')

makejoy_latest/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> -->
    <title>Make Joy</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->


{% if request.user.is_anonymous %}
    {% block content %}
    {% endblock %}
{% endif %}
{% if request.user.is_authenticated %}
    {% block content1 %}
    {% endblock %}
{% endif %}


<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}

{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

makejoy_latest/templates/common/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style copy.css' %}">
<div class="container">
    <h1>로그인</h1>
    <form method="post" action="{% url 'common:login1' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <label for="E-mail">사용자 이름</label>
        <input type="text" class="form-control" name="username" id="username"
               value="{{ form.username.value|default_if_none:'' }}">
        <label for="password">비밀번호</label>

        <input type="password" class="form-control" name="password" id="password"
               value="{{ form.password.value|default_if_none:'' }}">
        <button type="submit">로그인</button>
    </form>
    <div class="options">
        <a href="{% url 'common:signup' %}">계정이 없으신가요?</a>
    </div>
</div>
{% endblock %}

makejoy_latest/templates/common/signup.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style copy.css' %}">
<div class="container my-3">
    <h1>회원가입</h1>
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

makejoy_latest/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    {% for error in form.non_field_errors %}  <!-- 넌필드 오류를 출력한다. -->
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

makejoy_latest/templates/index/index.html
{% extends 'base.html' %}

{% load static %}
{% block content1 %}
<link rel="stylesheet" type="text/css" href="{% static 'profile.css' %}">
<div class="wrapper">
    <div class="img-area">
      <div class="inner-area">
        <img src="static\icon\boogi_2.png">
      </div>
    </div>
    <div class="icon arrow"><i class="fas fa-arrow-left"></i></div>
    <div class="icon dots"><i class="fas fa-ellipsis-v"></i></div>
    <div class="name">{{ user.username }}</div>
    <div class="about">Developer</div>
    <div class="social-icons">
      <a href="#" class="kakaotalk" onclick="location.href='https://open.kakao.com/o/goaPJP7e'"><img src="{%static 'icon/kakaotalk.png' %}"/></a>
      <a href="#" class="git" onclick="location.href='https://github.com/lullu303/subs_info_pjt'"><img src="{%static 'icon/git.png' %}"></i></a>
      <a href="#" class="instagram" onclick="location.href='https://www.instagram.com/special_jejudo/'"><img src="{%static 'icon/instagram.png' %}" /></a>
      <a href="#" class="youtube" onclick="location.href='https://www.youtube.com/'"><img src="{%static 'icon/youtube.png' %}"></i></a>
    </div>
    <div class="buttons">

      
      <a href= "{% url 'memo:memo_name' %}">Diary</a>
      <a href= "{% url 'calendar1:calendar1_name' %}">Calendar</a>
      <a href= "{% url 'todo:todo_name' %}">ToDo</a>
      <a href= "{% url 'weather:weather_name' %}">Weather</a>
   
    </div>
    <div class="social-share">

      <div class="row">
        <a>데이터 분석 서비스 개발자 7기</a>
      </div>
    </div>
  </div>
{% endblock %}

makejoy_latest/templates/memo/diarymemo.html
{% extends 'base.html' %}
{% load static %}
{% block content1 %}

<html>
  <head>
    <title>일기장</title>
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href= "{% static 'diarymemo.css' %}" type="text/css" media="screen" charset="utf-8">    
  </head>
  <body>
    <div class="container">
      <p>
        <label for="new-task">Add diary</label>
        <input id="new-task" type="text">
        <button>Add</button>
      </p>
      
      <h3>diary</h3>
      <ul id="incomplete-tasks">
        <li>
          <label>운동갔다가 병원들렸다.</label>
          <input type="text">
          <button class="edit">Edit</button>
          <button class="delete">Delete</button>
        </li>
        <li class="editMode">
          <label>맥도날드 사왔는데 너무 맛있었다.</label>
          <input type="text" value="맥도날드 사왔는데 너무 맛있었다.">
          <button class="edit">Edit</button>
          <button class="delete">Delete</button>
        </li>
      </ul>
    </div>
  </body>
</html>

<script src="{%static 'diarymemo.js'%}"></script>
{% endblock %}

makejoy_latest/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index:index' %}">Make Joy</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login1' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

makejoy_latest/templates/todo/todo.html
{% extends 'base.html' %}
{% load static %}
{% block content1 %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" type="text/css" href="{% static 'todo.css' %}">
</head>

<body>
    <div class="wrapper">
        <div class="task-input">
           <a href="{% url 'index:index' %}"> <img class = "icon1" src="{% static 'icon/home.svg' %}" alt="icon1"></a>
            <input type="text" placeholder="작업 추가하기">
        </div>
        <div class="controls">
            <div class="filters">
                <span id="all" class="active">
                    모두 표시
                </span>
                <span id="pending">진행중</span>
                <span id="completed">완료됨</span>
            </div>
            <button class="clear-btn">모두 지우기</button>
        </div>
        <ul class="task-box"></ul>
    </div>
    <script src ="{% static 'todo.js' %}"></script>
</body>

</html>
{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style copy.css' %}">
<div class="container">
    <h1>로그인</h1>
    <form method="post" action="{% url 'common:login1' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <label for="E-mail">사용자 이름</label>
        <input type="text" class="form-control" name="username" id="username"
               value="{{ form.username.value|default_if_none:'' }}">
        <label for="password">비밀번호</label>

        <input type="password" class="form-control" name="password" id="password"
               value="{{ form.password.value|default_if_none:'' }}">
        <button type="submit">로그인</button>
    </form>
    <div class="options">
        <a href="#">비밀번호를 잊어버리셨나요?</a>
        <a href="#">계정이 없으신가요?</a>
    </div>
</div>
{% endblock %}