common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login1'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
   
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from index.views import base_views
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('todo/', include('todo.urls')),
    path('memo/', include('memo.urls')),
    path('weather/', include('weather.urls')),
    path('calendar1/', include('calendar1.urls')),



]

make_joy/config/urls.py
from django.contrib import admin
from django.urls import path, include

from index.views import base_views
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('todo/', include('todo.urls')),
    path('memo/', include('memo.urls')),
    path('weather/', include('weather.urls')),
    path('calendar1/', include('calendar1.urls')),



]

makejoy_latest/calendar1/urls.py
from django.urls import path
from . import views

app_name = 'calendar1'

urlpatterns = [
    path('', views.calendar1_view, name='calendar1_name'),
]

makejoy_latest/common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login1'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
 

]

makejoy_latest/config/urls.py
from django.contrib import admin
from django.urls import path, include

from index.views import base_views
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('todo/', include('todo.urls')),
    path('memo/', include('memo.urls')),
    path('weather/', include('weather.urls')),
    path('calendar1/', include('calendar1.urls')),

]

makejoy_latest/index/urls.py
from django.urls import path

from .views import base_views

app_name = 'index'

urlpatterns = [
    path('', base_views.index, name='index'),
]

makejoy_latest/memo/urls.py
from django.urls import path
from . import views

app_name = 'memo'

urlpatterns = [
    path('', views.memo_view, name='memo_name'),
]

makejoy_latest/password/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

appname='password'

urlpatterns = [
    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

makejoy_latest/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_view, name='todo_name'),
]

makejoy_latest/weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.weather_view, name='weather_name'),
]

index/models.py
from django.contrib.auth.models import User
from django.db import models


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

makejoy_latest/index/models.py
# from django.contrib.auth.models import User
# from django.db import models

makejoy_latest/todo/models.py
from django.db import models

# Create your models here.

index/forms.py
from django import forms
from index.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

makejoy_latest/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

makejoy_latest/index/forms.py
# from django import forms
# from index.models import Question, Answer

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

index/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from index.models import Question


def index(request):
    return render(request, 'index/index.html')

makejoy_latest/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

makejoy_latest/memo/views.py
from django.shortcuts import render

# Create your views here.
def memo_view(request):

        return render(request, 'memo/diarymemo.html')

makejoy_latest/password/views.py
from django.shortcuts import render

# Create your views here.
def password_reset(request):
    return render(request, 'password/password_reset.html')

makejoy_latest/todo/views.py
from django.shortcuts import render


def todo_view(request):

        return render(request, 'todo/todo.html')

makejoy_latest/weather/views.py
from django.shortcuts import render


def weather_view(request):

        return render(request, 'weather/weather_api.html')

make_joy/templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">


<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>
<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>
<form action="{% url 'pybo:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="content" id="content" rows="15"></textarea>
<input type="submit" value="답변등록">
</form>

make_joy/templates/pybo/question_list.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}

templates/index/index.html
{% extends 'base.html' %}

{% load static %}
{% block content1 %}
<link rel="stylesheet" type="text/css" href="{% static 'profile.css' %}">
<div class="wrapper">
    <div class="img-area">
      <div class="inner-area">
        <img src="static\icon\boogi_2.png">
      </div>
    </div>
    <div class="icon arrow"><i class="fas fa-arrow-left"></i></div>
    <div class="icon dots"><i class="fas fa-ellipsis-v"></i></div>
    <div class="name">{{ user.username }}</div>
    <div class="about">Developer</div>
    <div class="social-icons">
      <a href="#" class="kakaotalk" onclick="location.href='https://open.kakao.com/o/goaPJP7e'"><img src="{%static 'icon/kakaotalk.png' %}"/></a>
      <a href="#" class="git" onclick="location.href='https://github.com/lullu303/subs_info_pjt'"><img src="{%static 'icon/git.png' %}"></i></a>
      <a href="#" class="instagram" onclick="location.href='https://www.instagram.com/special_jejudo/'"><img src="{%static 'icon/instagram.png' %}" /></a>
      <a href="#" class="youtube" onclick="location.href='https://www.youtube.com/'"><img src="{%static 'icon/youtube.png' %}"></i></a>
    </div>
    <div class="buttons">

      
      <a href= "{% url 'memo:memo_name' %}">Diary</a>
      <a href= "{% url 'calendar1:calendar1_name' %}">Calendar</a>
      <a href= "{% url 'todo:todo_name' %}">ToDo</a>
      <a href= "{% url 'weather:weather_name' %}">Weather</a>
   
    </div>
    <div class="social-share">

      <div class="row">
        <a>데이터 분석 서비스 개발자 7기</a>
      </div>
    </div>
  </div>
{% endblock %}

templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">


<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>
<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>
<form action="{% url 'pybo:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="content" id="content" rows="15"></textarea>
<input type="submit" value="답변등록">
</form>

templates/pybo/question_list.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}